-- DROP DATABASE
DROP DATABASE IF EXISTS techBlog_db;

-- CREATE DATABASE
CREATE DATABASE techBlog_db;

-- USE DATABASE
USE techBlog_db;

-- User Table

CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT,
    username: VARCHAR(30) NOT NULL UNIQUE,
    password: VARCHAR(200) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)

-- Blog Title Table
CREATE TABLE blogEntry (
    id INT NOT NULL AUTO_INCREMENT,
    blog_title VARCHAR(300) NOT NULL,
    blog_content TEXT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);

-- Comments Table

CREATE TABLE comments (
    id INT NOT NULL AUTO_INCREMENT,
    comment_content TEXT NOT NULL,
    post_id INT NOT NULL,
    user_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FOREIGN KEY (post_id) REFERENCES blogEntry(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
)